export const NIGERIAN_BANKS = [
  { name: "Access Bank", code: "000014" },
  { name: "Access (Diamond)", code: "000005" },
  { name: "Ecobank", code: "000010" },
  { name: "FCMB", code: "000003" },
  { name: "Fidelity Bank", code: "000007" },
  { name: "First Bank", code: "000016" },
  { name: "Globus Bank", code: "000027" },
  { name: "Guaranty Trust Bank", code: "000013" },
  { name: "Heritage Bank", code: "000020" },
  { name: "Keystone Bank", code: "000002" },
  { name: "Kuda MFB", code: "090267" },
  { name: "LOTUS Bank", code: "000029" },
  { name: "Optimum Trust Bank", code: "100036" },
  { name: "Premium Trust Bank", code: "000031" },
  { name: "Rubies (Highstreet) MFB", code: "090175" },
  { name: "Stanbic Bank", code: "000012" },
  { name: "Sterling Bank", code: "000001" },
  { name: "UBA", code: "000004" },
  { name: "Union Bank", code: "000018" },
  { name: "Unity Bank", code: "000011" },
  { name: "VFD Bank", code: "090110" },
  { name: "Wema Bank", code: "000017" },
  { name: "Zenith Bank", code: "000015" },
];

export const NIGERIAN_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const INDUSTRIES = [
  "Technology",
  "Finance",
  "Healthcare",
  "Education",
  "Manufacturing",
  "Government",
  "Retail",
  "Logistics",
  "Construction",
  "Agriculture",
  "Media",
  "Legal",
  "Other",
];

export const COMPANY_SIZES = ["1-10", "11-50", "51-200", "201-500", "500+"];
export const GENDER_OPTIONS = ["Male", "Female", "Prefer not to say"];
